Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 3, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 3, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 12, in <module>
    for features in resultats["features"]:
                    ~~~~~~~~~^^^^^^^^^^^^
KeyError: 'features'
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
Traceback (most recent call last):
  File "/home/simon/velo-tbm/collector.py", line 22, in <module>
    cur.execute(f"""
sqlite3.OperationalError: no such table: velos
